// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/clusters" | "/admin/heatmap" | "/admin/logs" | "/cart" | "/checkout" | "/dashboard" | "/login" | "/orders" | "/products/[id]" | "/signup" | "/vendor" | "/vendor/analytics" | "/vendor/orders" | "/vendor/products" | "/vendor/store"
type AppRouteHandlerRoutes = "/api/admin/users" | "/api/analytics/cluster-competition" | "/api/analytics/cluster-demand" | "/api/analytics/cluster-intelligence" | "/api/auth/login" | "/api/auth/me" | "/api/auth/signup" | "/api/cart" | "/api/cart/[id]" | "/api/cart/add" | "/api/cart/clear" | "/api/cart/remove" | "/api/cart/update" | "/api/checkout" | "/api/orders" | "/api/products" | "/api/products/[id]" | "/api/products/search" | "/api/stores" | "/api/stores/[id]" | "/api/vendor/analytics" | "/api/vendor/orders" | "/api/vendor/products" | "/api/vendor/products/[id]" | "/api/vendor/store"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard" | "/vendor"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/clusters": {}
  "/admin/heatmap": {}
  "/admin/logs": {}
  "/api/admin/users": {}
  "/api/analytics/cluster-competition": {}
  "/api/analytics/cluster-demand": {}
  "/api/analytics/cluster-intelligence": {}
  "/api/auth/login": {}
  "/api/auth/me": {}
  "/api/auth/signup": {}
  "/api/cart": {}
  "/api/cart/[id]": { "id": string; }
  "/api/cart/add": {}
  "/api/cart/clear": {}
  "/api/cart/remove": {}
  "/api/cart/update": {}
  "/api/checkout": {}
  "/api/orders": {}
  "/api/products": {}
  "/api/products/[id]": { "id": string; }
  "/api/products/search": {}
  "/api/stores": {}
  "/api/stores/[id]": { "id": string; }
  "/api/vendor/analytics": {}
  "/api/vendor/orders": {}
  "/api/vendor/products": {}
  "/api/vendor/products/[id]": { "id": string; }
  "/api/vendor/store": {}
  "/cart": {}
  "/checkout": {}
  "/dashboard": {}
  "/login": {}
  "/orders": {}
  "/products/[id]": { "id": string; }
  "/signup": {}
  "/vendor": {}
  "/vendor/analytics": {}
  "/vendor/orders": {}
  "/vendor/products": {}
  "/vendor/store": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
  "/vendor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
