var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/clusters/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b8263177._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_97cddf77._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28b4e4a3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d5ae7ad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_438bd751._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_07d69fb5._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_clusters_page_actions_0a526d85.js")
R.m(19892)
module.exports=R.m(19892).exports
