var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__81740e0b._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_a1322970._.js")
R.c("server/chunks/ssr/[root-of-the-server]__28b4e4a3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d5ae7ad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_438bd751._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_orders_page_actions_bf8b1ceb.js")
R.m(9901)
module.exports=R.m(9901).exports
